### ISSUE TITLE
No output after running

### ISSUE THREAD

**Issue by tlindsay8** [beeware/batavia#738] opened 2018-04-07 14:37 UTC
## Expected Behavior

Hey I'm a first time contributor, I typed print("Hello World") in the browser and expected it to be in the console browser.

## Current Behavior

When I clicked the run code button nothing appeared in the console output area.
## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)
Python version 3.5.2
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [ ] Windows
  - [16.04 LTS ] Ubuntu

**Comment by freakboy3742** [comment] 2018-04-07 23:50
@tlindsay8 Thanks for the report. We need a bit more detail to help diagnose what is going on here. 

When you say console, do you mean the Javascript console, or the console part of the webpage? 

You say you're not getting errors in the console - are you getting *anything*?

**Comment by tlindsay8** [comment] 2018-04-09 23:16
@freakboy3742 I'm getting this error:
ReferenceError: batavia is not defined[Learn More]  localhost:8000:             412:5

**Comment by freakboy3742** [comment] 2018-04-10 22:55
@tlindsay8 Right - that sounds like something has gone wrong in the install phase, and you've missed (or ignored) an error message.

If you delete the `node_modules` directory and then re-run the `npm run build` step, that should clean up the problem - however, you'll need to check that you've got the right versions of Node and NPM. If you don't, you'll get an error building the batavia library, which would result in the error you've seen.

**Comment by martica** [comment] 2019-05-21 14:01
Were you able to get running by redoing the `npm run build` step, @tlindsay8? It looks like that step didn't complete successfully and batavia.js wasn't available from your error description.

**Comment by martica** [comment] 2019-06-02 19:42
I'm going to close this for now. If you can reproduce this still, please reopen the issue.

**Closed by martica** 2019-06-02 19:42 UTC
Labels: fix-verification-requested
