### ISSUE TITLE
Unable to setup Batavia: webpack --progress error

### ISSUE THREAD

**Issue by SashwatAnagolum** [beeware/batavia#771] opened 2019-01-21 05:19 UTC
## Expected Behavior

Batavia is set up successfully.

## Current Behavior

'npm run build' throws an error:

Screenshots of the terminal I was running these commands in:
![image](https://user-images.githubusercontent.com/42544553/51453993-7d72f180-1d68-11e9-993f-3587c7e105b7.png)

![image](https://user-images.githubusercontent.com/42544553/51454497-fecb8380-1d6a-11e9-97d7-4b0e6188547b.png)

## Steps to reproduce

1. Fork the batavia repo, and then clone it;

2. Running Python 3.5.0 and Node 6.9.1, perform the sequence of instructions as given in the [preparation tutorial](https://batavia.readthedocs.io/en/latest/tutorial/tutorial-0.html) until you reach the 'npm run build' command;

3.Run 'npm run build'.

I've been trying to figure out the problem for a while now, but with no success. I even tried running different versions of Python and Node, but each try gave me the same error.

The logs are here: 
[2019-01-21T05_00_37_130Z-debug.log](https://github.com/pybee/batavia/files/2777616/2019-01-21T05_00_37_130Z-debug.log)

I would really appreciate it if someone could help clear this up for me.

## Your Environment

* Python Version (list the specific version number)
I have three versions installed, and use virtualenv:
3.7.2
3.4.3
3.5.0  *using

* Node Version 
I have two versions installed, and use nvm:
10.15.0
6.9.1 *using

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [*] Windows 10 Pro
  - [ ] Ubuntu

**Comment by danyeaw** [comment] 2019-01-21 22:34
Thanks for your contribution by submitting the issue. It looks like I temporarily broke things while updating dependencies, sorry about that. #770 should fix this once merged 😀

**Comment by martica** [comment] 2019-05-21 01:11
@SashwatAnagolum Have you had a chance to try reproducing this since @danyeaw merge #770?

**Comment by martica** [comment] 2019-06-02 19:43
I'm going to close this for now. If you can reproduce this still, please reopen the issue.

**Closed by martica** 2019-06-02 19:43 UTC
Labels: fix-verification-requested
