### ISSUE TITLE
Operator overloading

### ISSUE THREAD

**Issue by artyprog** [beeware/batavia#593] opened 2017-07-23 22:00 UTC
Hy All,

Thanks for Batavia.
Will operator overloading be doable ?

```
class Point:
    def __init__(self, x = 0, y = 0):
        self.x = x
        self.y = y
    
    def __str__(self):
        return "({0},{1})".format(self.x,self.y)
    
    def __add__(self,other):
        x = self.x + other.x
        y = self.y + other.y
        return Point(x,y)
    
    
p1 = Point(2,3)
print(p1+p1)
```

```
Traceback (most recent call last):
  File "/tmp/tmp8xlszin9", line 16, in <module>
TypeError: TypeError: items[0].__add__ is not a function
```

Regards

**Comment by freakboy3742** [comment] 2017-07-24 00:30
It's entirely *doable* - Batavia evidently has a bug in this particular case. If you want to dig into why, that would be a very helpful contribution.

**Comment by artyprog** [comment] 2017-07-24 13:26
I am better at finding bugs than resolve them:-)

But I will try

Regards

**Comment by Utsal20** [comment] 2017-07-27 17:02
I believe you will need a decorator before def __add__ @artyprog

**Comment by artyprog** [comment] 2017-07-31 13:27
As suggested  by Utsal Shrestha I  have tried using a decorator,
but the wrapper function  is not called and get the same error...

**Comment by martica** [comment] 2019-05-21 01:04
Looks like @xitij2000's PR fixed this. I'm going to close it out. Feel free to reopen it if you can still reproduce it, @artyprog.

**Closed by martica** 2019-05-21 01:04 UTC
