### ISSUE TITLE
Runserver fails in linux

### ISSUE THREAD

**Issue by igormcoelho** [beeware/batavia#717] opened 2018-02-22 20:46 UTC
## Expected Behavior

Expected code is executed after clicked "Run your code"

## Current Behavior

Nothing happens on localhost:8000, but on terminal, error 404 arises:

Django version 1.10, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[22/Feb/2018 20:43:27] "POST / HTTP/1.1" 200 26106
[22/Feb/2018 20:43:27] "GET /static/native.js HTTP/1.1" 304 0
[22/Feb/2018 20:43:27] "GET /static/CodeMirror/lib/codemirror.js HTTP/1.1" 304 0
[22/Feb/2018 20:43:27] "GET /static/CodeMirror/lib/codemirror.css HTTP/1.1" 304 0
[22/Feb/2018 20:43:27] "GET /static/CodeMirror/mode/python/python.js HTTP/1.1" 304 0
[22/Feb/2018 20:43:27] "GET /static/styles/styles.css HTTP/1.1" 304 0
[22/Feb/2018 20:43:27] "GET /static/batavia.js HTTP/1.1" 404 1643
[22/Feb/2018 20:43:27] "GET /static/batavia.js HTTP/1.1" 404 1643

## Steps to reproduce

1. Run tutorial

2. http://batavia.readthedocs.io/en/latest/tutorial/tutorial-1.html

## Your Environment

* Python Version (list the specific version number)

Python 3.5.2

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

Ubuntu 16.04.1

  - [ ] OSX
  - [X ] Linux
  - [ ] Windows
  - [ ] Ubuntu

**Comment by freakboy3742** [comment] 2018-02-23 01:31
If you're getting a 404, it sounds like you've missed a step from the setup instructions, or one of those steps raised an error.

This may be due to an incompatible NPM or Node version; or an incomplete Batavia build.

The easiest way to restart things is to delete the `node_packages` directory, then re-reun steps 4 and 5 from [Tutorial 0](http://batavia.readthedocs.io/en/latest/tutorial/tutorial-0.html).

**Comment by martica** [comment] 2019-05-21 01:43
@igormcoelho Can you confirm if you were able to get this work after following [Tutorial 0](http://batavia.readthedocs.io/en/latest/tutorial/tutorial-0.html)? You call out tutorial 1 specifically in your steps to reproduce, but don't mention 0. If the `npm run build` command wasn't run you would see this behaviour.

**Comment by martica** [comment] 2019-06-02 19:42
I'm going to close this for now. If you can reproduce this still, please reopen the issue.

**Closed by martica** 2019-06-02 19:42 UTC
Labels: fix-verification-requested
